# Minimal stub for torch — optional dep used only in drl_agent.py
from __future__ import annotations

from typing import Any

# Dtype aliases
float16: Any = ...
float32: Any = ...
float64: Any = ...
int8: Any = ...
int16: Any = ...
int32: Any = ...
int64: Any = ...
bool: Any = ...

class onnx:  # noqa: N801
    """Stub for torch.onnx sub-module."""
    @staticmethod
    def export(  # type: ignore[misc]
        model: Any,
        args: Any,
        f: Any,
        *,
        opset_version: int = 17,
        input_names: list[str] | None = None,
        output_names: list[str] | None = None,
        dynamic_axes: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None: ...

class Tensor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def numpy(self) -> Any: ...
    def item(self) -> float: ...
    def float(self) -> Tensor: ...
    def long(self) -> Tensor: ...
    def to(self, device: Any) -> Tensor: ...

def tensor(data: Any, *args: Any, **kwargs: Any) -> Tensor: ...
def zeros(*size: int, **kwargs: Any) -> Tensor: ...
def ones(*size: int, **kwargs: Any) -> Tensor: ...
def load(f: Any, *args: Any, **kwargs: Any) -> Any: ...
def save(obj: Any, f: Any, *args: Any, **kwargs: Any) -> None: ...
def no_grad() -> Any: ...

class nn:  # noqa: N801
    class Module:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def forward(self, *args: Any, **kwargs: Any) -> Any: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        def parameters(self) -> Any: ...
        def load_state_dict(self, state_dict: Any, *args: Any, **kwargs: Any) -> Any: ...
        def state_dict(self) -> dict[str, Any]: ...
        def eval(self) -> nn.Module: ...
        def train(self, mode: bool = True) -> nn.Module: ...

    class Linear:
        def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...

class optim:  # noqa: N801
    class Adam:
        def __init__(self, params: Any, lr: float = 0.001, **kwargs: Any) -> None: ...
        def zero_grad(self) -> None: ...
        def step(self) -> None: ...
