# GitHub Sponsors & Funding
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: []
open_collective: ""
ko_fi: ""
tidelift: ""
community_bridge: ""
liberapay: ""
issuehunt: ""
lfx_crowdfunding: ""
otechie: ""
polar: ""
custom:
  - "https://bess-solutions.cl/sponsor"
  - "https://github.com/bess-solutions/open-bess-edge/discussions/1"
