# Minimal stub for ray.rllib.algorithms
from __future__ import annotations
from typing import Any

class Algorithm:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def train(self) -> dict[str, Any]: ...
    def compute_single_action(self, obs: Any, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, checkpoint_dir: str) -> str: ...
    def restore(self, checkpoint_path: str) -> None: ...
    def stop(self) -> None: ...
