# Minimal stub for ray.rllib.algorithms.ppo
from __future__ import annotations
from typing import Any

class PPOConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def environment(self, env: Any, *args: Any, **kwargs: Any) -> PPOConfig: ...
    def rollouts(self, *args: Any, **kwargs: Any) -> PPOConfig: ...
    def training(self, *args: Any, **kwargs: Any) -> PPOConfig: ...
    def resources(self, *args: Any, **kwargs: Any) -> PPOConfig: ...
    def rl_module(self, *args: Any, **kwargs: Any) -> PPOConfig: ...
    def to_dict(self) -> dict[str, Any]: ...
    def build(self) -> PPO: ...

class PPO:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def train(self) -> dict[str, Any]: ...
    def save(self, checkpoint_dir: str) -> str: ...
