# Minimal stub for ray.rllib.policy
from __future__ import annotations

from typing import Any

class Policy:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def compute_actions(self, obs: Any, *args: Any, **kwargs: Any) -> tuple[Any, Any, Any]: ...
    def get_weights(self) -> dict[str, Any]: ...
    def set_weights(self, weights: dict[str, Any]) -> None: ...
