# Minimal stub for ray — optional dependency not available on Python 3.14
# This suppresses reportMissingImports while keeping full type safety guards.

from __future__ import annotations

from typing import Any

def init(*args: Any, **kwargs: Any) -> None: ...
def shutdown(*args: Any, **kwargs: Any) -> None: ...
def is_initialized() -> bool: ...
def remote(*args: Any, **kwargs: Any) -> Any: ...
def get(object_refs: Any, *args: Any, **kwargs: Any) -> Any: ...
def put(value: Any, *args: Any, **kwargs: Any) -> Any: ...

class ObjectRef:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class remote:  # noqa: N801 – mirrors ray's decorator
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def remote(self, *args: Any, **kwargs: Any) -> Any: ...
